version: 2

models:
  # table level 
  - name: superstore_fact
    description: "Fact table containing one row per order with revenue metrics."
    # column level
    columns:
      - name: id
        description: "Primary key for the fact table."
        tests:
          - unique
          - not_null

      - name: customer_key
        description: "Foreign key to the dim_customers table."
        tests:
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_id

      - name: store_key
        description: "Foreign key to the dim_stores table."
        tests:
          - relationships:
              arguments:
                to: ref('dim_stores')
                field: store_id

      - name: product_key
        description: "Foreign key to the dim_product table."
        tests:
          - relationships:
              arguments:
                to: ref('dim_product')
                field: product_id

      - name: category_key
        description: "Foreign key to the dim_category table."
        tests:
          - relationships:
              arguments:
                to: ref('dim_category')
                field: category_id

  # table level         
  - name: dim_customer
    description: "Dimension table with one row per customer."
    columns:
      - name: customer_id
        description: "Primary key for the customer."
        tests:
          - unique
          - not_null

  # table level       
  - name: dim_category
    description: "Dimension table with one row per category."
    columns:
      - name: category_id
        description: "Primary key for the category."
        tests:
          - unique
          - not_null

  # table level        
  - name: dim_product
    description: "Dimension table with one row per product."
    columns:
      - name: product_id
        description: "Primary key for the product."
        tests:
          - unique
          - not_null

  # table level
  - name: dim_stores
    description: "Dimension table with one row per store."
    columns:
      - name: store_id
        description: "Primary key for the store."
        tests:
          - unique
          - not_null
