# dbt_project.yml
name: 'ELT_project_dbt'
version: '1.0.0'
config-version: 2

profile: 'ELT_project_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ELT_project_dbt:
    # Configs applied to all files under models/staging/
    staging:
      +materialized: view
      +schema: staging
    # Configs applied to all files under models/warehouse/
    marts:
      +materialized: table
      +schema: analytics